// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAPKy7F8xZ5ZVuREIJRhAArcOJB3cOQ7Eg",
      authDomain: "flutter-gestion-tache-firebase.firebaseapp.com",
      projectId: "flutter-gestion-tache-firebase",
      storageBucket: "flutter-gestion-tache-firebase.appspot.com",
      messagingSenderId: "965723048235",
      appId: "1:965723048235:web:92d628aeeb4f758ef61d6e");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyAPKy7F8xZ5ZVuREIJRhAArcOJB3cOQ7Eg",
      authDomain: "flutter-gestion-tache-firebase.firebaseapp.com",
      projectId: "flutter-gestion-tache-firebase",
      storageBucket: "flutter-gestion-tache-firebase.appspot.com",
      messagingSenderId: "965723048235",
      appId: "1:965723048235:web:92d628aeeb4f758ef61d6e");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAPKy7F8xZ5ZVuREIJRhAArcOJB3cOQ7Eg",
    authDomain: "flutter-gestion-tache-firebase.firebaseapp.com",
    projectId: "flutter-gestion-tache-firebase",
    storageBucket: "flutter-gestion-tache-firebase.appspot.com",
    messagingSenderId: "965723048235",
    appId: "1:965723048235:web:92d628aeeb4f758ef61d6e",
    iosClientId:
        '472384201308-2572lg0u5uu4cdulr3r2shv10pnsccee.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestionTache',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyAPKy7F8xZ5ZVuREIJRhAArcOJB3cOQ7Eg",
    authDomain: "flutter-gestion-tache-firebase.firebaseapp.com",
    projectId: "flutter-gestion-tache-firebase",
    storageBucket: "flutter-gestion-tache-firebase.appspot.com",
    messagingSenderId: "965723048235",
    appId: "1:965723048235:web:92d628aeeb4f758ef61d6e",
    iosClientId:
        '472384201308-no6hg6g6j1cg8f5qavj735jd78j9pq4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestionTache.RunnerTests',
  );
}
